Issue5 説明画面のHTML、CSS追加
recursion-team-o/typing-game pull request #29
Opened 2022-03-09 05:03 UTC by Lukeyusukemiura

## Issue
-- issue5:  説明画面のHTML、CSS追加

## レビューしてもらいたい箇所
-- 箇条書きになっていること
-- メインの戻るでしっかりとメインに戻れるか

## やったこと
-- AboutViewのHTMLとCSSを追加
-- またRouterlinkを追加し、「メインの戻る」でメインに戻れるようにした。

## やらなかったこと
-- スタート画面へのRouterlinkの追加
----スタートが押された時にゲーム画面に飛ぶということはゲーム画面が作成されてからやろうと思っています。

2022-03-09 14:59 UTC, haruki111 commented on src/views/AboutView.vue
> +          <div class="text-2xl px-0">レベル：　２</div>
"レベル:_2" のスペースが全角になっているので、半角に修正お願いします

2022-03-09 15:37 UTC, haruki111 commented
メインに戻ることは確認しました。
コメント計四点修正お願いします

2022-03-10 04:17 UTC, haruki111 requested changes

2022-03-10 04:44 UTC, tojimasan commented on src/views/AboutView.vue
> +          <div class="text-2xl px-0">レベル：　２</div>
[nits]
Javascript → JavaScriptでお願いします。

2022-03-10 13:54 UTC, haruki111 commented on src/views/AboutView.vue
> +</style>
[nit pick]
- htmlのクラス名を書く際はケバブケースで
例) rulebox -> rule-box

- セレクタの後は空白で
例) .welcomebox{} ->  .welcombox_{}

2022-03-10 13:54 UTC, haruki111 commented on src/views/AboutView.vue
> +      </ol>
[ask]
今、”・”などの装飾がありませんが、付けないのでしょうか？
もし付けるのであれば、"list-disc"を< ol >タグのクラスに付けてください。

2022-03-10 13:54 UTC, haruki111 commented on src/views/AboutView.vue
> +        <li class="text-5xl pb-4">ルール:</li>
"ルール"はリストの要素ではないので、< ol >タグの外に書いてください

2022-03-11 14:25 UTC, haruki111 approved these changes
![LGTM](https://image.lgtmoon.dev/12838)

2022-03-12 08:23 UTC, hata8341 approved these changes
ハルキさんの修正点が完了すれば、大丈夫だと思います

2022-03-13 06:53 UTC, merged